---
# VLAN and SVI configuration for a new network

- name: Create VLAN
  cisco.nxos.nxos_vlans:
    config:
      - vlan_id: "{{ vlan }}"
        name: "{{ name }}"
        state: active

- name: Create VLAN Interface
  cisco.nxos.nxos_interfaces:
    config:
      - name: "vlan{{ vlan }}"
        enabled: true

- name: Create SVI and assign to VRF
  cisco.nxos.nxos_vrf_interface:
    vrf: "{{ vrf }}"
    interface: "vlan{{ vlan }}"
    state: present

- name: Apply IP to SVI
  cisco.nxos.nxos_l3_interfaces:
    config:
    - name: "vlan{{ vlan }}"
      ipv4:
      - address: "192.168.{{ vlan }}.2/24"
        tag: 123

- name: Configure HSRP for the SVI
  cisco.nxos.nxos_hsrp:
    group: "{{ vlan }}"
    interface: "vlan{{ vlan }}"
    vip: "192.168.{{ vlan }}.1"
    priority: 110
    preempt: enabled
