---
- name: Configure switch
  hosts: all
  gather_facts: false

  tasks:
  - name: Enable interface-vlan feature
    cisco.nxos.nxos_feature:
      feature: interface-vlan
      state: enabled

  - name: Enable HSRP feature 
    cisco.nxos.nxos_feature:
      feature: hsrp 
      state: enabled

  - name: Change hostname
    cisco.nxos.nxos_hostname:
      config:
        hostname: tres-ansible

  - name: Create chiefs vrf
    cisco.nxos.nxos_vrf:
      name: chiefs
      state: present

  - name: Create vlans
    cisco.nxos.nxos_vlans:
      config:
      - vlan_id: 15
        name: mahomes
        state: active
      - vlan_id: 87
        name: kelce
        state: active
      - vlan_id: 95
        name: jones
        state: active 

  - name: Create VLAN interfaces
    cisco.nxos.nxos_interfaces:
      config:
      - name: vlan15
        enabled: true
      - name: vlan87
        enabled: true
      - name: vlan95
        enabled: true

  - name: Assign vlan15 interface and assign to chiefs vrf
    cisco.nxos.nxos_vrf_interface:
      vrf: chiefs
      interface: vlan15
      state: present

  - name: Assign vlan87 interface and assign to chiefs vrf
    cisco.nxos.nxos_vrf_interface:
      vrf: chiefs
      interface: vlan87
      state: present

  - name: Assign vlan95 interface and assign to chiefs vrf
    cisco.nxos.nxos_vrf_interface:
      vrf: chiefs
      interface: vlan95
      state: present
 
  - name: Create SVI interface
    cisco.nxos.nxos_l3_interfaces:
      config:
      - name: vlan15
        ipv4:
        - address: 192.168.15.2/24
          tag: 123
      - name: vlan87
        ipv4:
        - address: 192.168.87.2/24
          tag: 123
      - name: vlan95
        ipv4:
        - address: 192.168.95.2/24
          tag: 123

  - name: Setup HSRP for VLAN 15
    cisco.nxos.nxos_hsrp:
      group: 15
      interface: vlan15
      vip: 192.168.15.1
      priority: 110
      preempt: enabled 

  - name: Setup HSRP for VLAN 87 
    cisco.nxos.nxos_hsrp:
      group: 87
      interface: vlan87
      vip: 192.168.87.1
      priority: 110
      preempt: enabled

  - name: Setup HSRP for VLAN 95
    cisco.nxos.nxos_hsrp:
      group: 95
      interface: vlan95
      vip: 192.168.95.1
      priority: 110
      preempt: enabled

  - name: Setup access ports
    cisco.nxos.nxos_interfaces:
      config:
        - name: eth1/5
          description: Mahomes
          mode: layer2
          enabled: true
        - name: eth1/6
          description: Kelce
          mode: layer2
          enabled: true
        - name: eth1/7
          description: Jones
          mode: layer2
          enabled: true

  - name: Assign VLANs to interfaces
    cisco.nxos.nxos_l2_interfaces:
      config:
      - name: eth1/5
        access: 
          vlan: 15
      - name: eth1/6
        access:
          vlan: 87
      - name: eth1/7
        access:
          vlan: 95
