---
# tasks for creating a VRF 
- name: Configure Access Interface 
  cisco.nxos.nxos_interfaces:
    config:
      - name: "{{ interface }}"
        description: "{{ description }}"
        mode: layer2
        enabled: true

- name: Assign VLAN to Interface
  cisco.nxos.nxos_l2_interfaces:
    config:
      - name: "{{ interface }}"
        access:
          vlan: "{{ vlan }}"
