---
- name: Basic switch setup
  hosts: all
  gather_facts: false

  tasks:
    - name: Remove SVI
      cisco.nxos.nxos_interfaces:
        config:
          - name: vlan13
        state: purged 

    - name: Remove VLAN
      cisco.nxos.nxos_vlans:
        config:
          - vlan_id: 13
        state: deleted

    - name: Delete VRF
      cisco.nxos.nxos_vrf:
        name: cheifs
        state: absent

